version: 2.1

orbs:
  go: circleci/go@1.7.0

jobs:
  build:
    docker:
      - image: cimg/go:1.17.5
    steps:
      - checkout
      - run: go version

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
